// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/truewebber/eve-online-mcp/internal/domain/authcode (interfaces: Repository)
//
// Generated by this command:
//
//	mockgen -destination=../../mocks/authcode.go -package=mocks -mock_names=Repository=MockAuthcodeRepository github.com/truewebber/eve-online-mcp/internal/domain/authcode Repository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	authcode "github.com/truewebber/eve-online-mcp/internal/domain/authcode"
	gomock "go.uber.org/mock/gomock"
)

// MockAuthcodeRepository is a mock of Repository interface.
type MockAuthcodeRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAuthcodeRepositoryMockRecorder
	isgomock struct{}
}

// MockAuthcodeRepositoryMockRecorder is the mock recorder for MockAuthcodeRepository.
type MockAuthcodeRepositoryMockRecorder struct {
	mock *MockAuthcodeRepository
}

// NewMockAuthcodeRepository creates a new mock instance.
func NewMockAuthcodeRepository(ctrl *gomock.Controller) *MockAuthcodeRepository {
	mock := &MockAuthcodeRepository{ctrl: ctrl}
	mock.recorder = &MockAuthcodeRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthcodeRepository) EXPECT() *MockAuthcodeRepositoryMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockAuthcodeRepository) Get(ctx context.Context, value string) (*authcode.Code, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, value)
	ret0, _ := ret[0].(*authcode.Code)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockAuthcodeRepositoryMockRecorder) Get(ctx, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockAuthcodeRepository)(nil).Get), ctx, value)
}

// Put mocks base method.
func (m *MockAuthcodeRepository) Put(ctx context.Context, c authcode.Code) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Put", ctx, c)
	ret0, _ := ret[0].(error)
	return ret0
}

// Put indicates an expected call of Put.
func (mr *MockAuthcodeRepositoryMockRecorder) Put(ctx, c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Put", reflect.TypeOf((*MockAuthcodeRepository)(nil).Put), ctx, c)
}

// SweepExpired mocks base method.
func (m *MockAuthcodeRepository) SweepExpired(ctx context.Context) (authcode.Swept, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SweepExpired", ctx)
	ret0, _ := ret[0].(authcode.Swept)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SweepExpired indicates an expected call of SweepExpired.
func (mr *MockAuthcodeRepositoryMockRecorder) SweepExpired(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SweepExpired", reflect.TypeOf((*MockAuthcodeRepository)(nil).SweepExpired), ctx)
}

// Take mocks base method.
func (m *MockAuthcodeRepository) Take(ctx context.Context, value string) (*authcode.Code, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Take", ctx, value)
	ret0, _ := ret[0].(*authcode.Code)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Take indicates an expected call of Take.
func (mr *MockAuthcodeRepositoryMockRecorder) Take(ctx, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Take", reflect.TypeOf((*MockAuthcodeRepository)(nil).Take), ctx, value)
}
