// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/truewebber/eve-online-mcp/internal/domain/character (interfaces: Repository)
//
// Generated by this command:
//
//	mockgen -destination=../../mocks/character.go -package=mocks -mock_names=Repository=MockCharacterRepository github.com/truewebber/eve-online-mcp/internal/domain/character Repository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	character "github.com/truewebber/eve-online-mcp/internal/domain/character"
	gomock "go.uber.org/mock/gomock"
)

// MockCharacterRepository is a mock of Repository interface.
type MockCharacterRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCharacterRepositoryMockRecorder
	isgomock struct{}
}

// MockCharacterRepositoryMockRecorder is the mock recorder for MockCharacterRepository.
type MockCharacterRepositoryMockRecorder struct {
	mock *MockCharacterRepository
}

// NewMockCharacterRepository creates a new mock instance.
func NewMockCharacterRepository(ctrl *gomock.Controller) *MockCharacterRepository {
	mock := &MockCharacterRepository{ctrl: ctrl}
	mock.recorder = &MockCharacterRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCharacterRepository) EXPECT() *MockCharacterRepositoryMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockCharacterRepository) Delete(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockCharacterRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockCharacterRepository)(nil).Delete), ctx, id)
}

// Get mocks base method.
func (m *MockCharacterRepository) Get(ctx context.Context, id int64) (*character.Character, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(*character.Character)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockCharacterRepositoryMockRecorder) Get(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockCharacterRepository)(nil).Get), ctx, id)
}

// ListByUser mocks base method.
func (m *MockCharacterRepository) ListByUser(ctx context.Context, userID string) ([]character.Character, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByUser", ctx, userID)
	ret0, _ := ret[0].([]character.Character)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByUser indicates an expected call of ListByUser.
func (mr *MockCharacterRepositoryMockRecorder) ListByUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByUser", reflect.TypeOf((*MockCharacterRepository)(nil).ListByUser), ctx, userID)
}

// UpdateRefresh mocks base method.
func (m *MockCharacterRepository) UpdateRefresh(ctx context.Context, id int64, fn func(string) (string, error)) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRefresh", ctx, id, fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateRefresh indicates an expected call of UpdateRefresh.
func (mr *MockCharacterRepositoryMockRecorder) UpdateRefresh(ctx, id, fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRefresh", reflect.TypeOf((*MockCharacterRepository)(nil).UpdateRefresh), ctx, id, fn)
}

// Upsert mocks base method.
func (m *MockCharacterRepository) Upsert(ctx context.Context, c character.Character) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upsert", ctx, c)
	ret0, _ := ret[0].(error)
	return ret0
}

// Upsert indicates an expected call of Upsert.
func (mr *MockCharacterRepositoryMockRecorder) Upsert(ctx, c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upsert", reflect.TypeOf((*MockCharacterRepository)(nil).Upsert), ctx, c)
}
