// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/truewebber/eve-online-mcp/internal/domain/confirm (interfaces: Repository)
//
// Generated by this command:
//
//	mockgen -destination=../../mocks/confirm.go -package=mocks -mock_names=Repository=MockConfirmRepository github.com/truewebber/eve-online-mcp/internal/domain/confirm Repository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	confirm "github.com/truewebber/eve-online-mcp/internal/domain/confirm"
	gomock "go.uber.org/mock/gomock"
)

// MockConfirmRepository is a mock of Repository interface.
type MockConfirmRepository struct {
	ctrl     *gomock.Controller
	recorder *MockConfirmRepositoryMockRecorder
	isgomock struct{}
}

// MockConfirmRepositoryMockRecorder is the mock recorder for MockConfirmRepository.
type MockConfirmRepositoryMockRecorder struct {
	mock *MockConfirmRepository
}

// NewMockConfirmRepository creates a new mock instance.
func NewMockConfirmRepository(ctrl *gomock.Controller) *MockConfirmRepository {
	mock := &MockConfirmRepository{ctrl: ctrl}
	mock.recorder = &MockConfirmRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConfirmRepository) EXPECT() *MockConfirmRepositoryMockRecorder {
	return m.recorder
}

// Count mocks base method.
func (m *MockConfirmRepository) Count(ctx context.Context, characterID int64) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Count", ctx, characterID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Count indicates an expected call of Count.
func (mr *MockConfirmRepositoryMockRecorder) Count(ctx, characterID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Count", reflect.TypeOf((*MockConfirmRepository)(nil).Count), ctx, characterID)
}

// Delete mocks base method.
func (m *MockConfirmRepository) Delete(ctx context.Context, value string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, value)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockConfirmRepositoryMockRecorder) Delete(ctx, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockConfirmRepository)(nil).Delete), ctx, value)
}

// DeleteExpired mocks base method.
func (m *MockConfirmRepository) DeleteExpired(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteExpired", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteExpired indicates an expected call of DeleteExpired.
func (mr *MockConfirmRepositoryMockRecorder) DeleteExpired(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteExpired", reflect.TypeOf((*MockConfirmRepository)(nil).DeleteExpired), ctx)
}

// Get mocks base method.
func (m *MockConfirmRepository) Get(ctx context.Context, value string) (*confirm.Confirm, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, value)
	ret0, _ := ret[0].(*confirm.Confirm)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockConfirmRepositoryMockRecorder) Get(ctx, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockConfirmRepository)(nil).Get), ctx, value)
}

// Put mocks base method.
func (m *MockConfirmRepository) Put(ctx context.Context, c confirm.Confirm) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Put", ctx, c)
	ret0, _ := ret[0].(error)
	return ret0
}

// Put indicates an expected call of Put.
func (mr *MockConfirmRepositoryMockRecorder) Put(ctx, c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Put", reflect.TypeOf((*MockConfirmRepository)(nil).Put), ctx, c)
}

// Take mocks base method.
func (m *MockConfirmRepository) Take(ctx context.Context, value string) (*confirm.Confirm, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Take", ctx, value)
	ret0, _ := ret[0].(*confirm.Confirm)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Take indicates an expected call of Take.
func (mr *MockConfirmRepositoryMockRecorder) Take(ctx, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Take", reflect.TypeOf((*MockConfirmRepository)(nil).Take), ctx, value)
}
