// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/truewebber/eve-online-mcp/internal/adapter/esi (interfaces: Client,TokenSource)
//
// Generated by this command:
//
//	mockgen -destination=../../mocks/esi.go -package=mocks -mock_names=Client=MockESIClient,TokenSource=MockESITokenSource github.com/truewebber/eve-online-mcp/internal/adapter/esi Client,TokenSource
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	esi "github.com/truewebber/eve-online-mcp/internal/adapter/esi"
	gomock "go.uber.org/mock/gomock"
)

// MockESIClient is a mock of Client interface.
type MockESIClient struct {
	ctrl     *gomock.Controller
	recorder *MockESIClientMockRecorder
	isgomock struct{}
}

// MockESIClientMockRecorder is the mock recorder for MockESIClient.
type MockESIClientMockRecorder struct {
	mock *MockESIClient
}

// NewMockESIClient creates a new mock instance.
func NewMockESIClient(ctrl *gomock.Controller) *MockESIClient {
	mock := &MockESIClient{ctrl: ctrl}
	mock.recorder = &MockESIClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockESIClient) EXPECT() *MockESIClientMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockESIClient) Delete(ctx context.Context, path string, characterID *int, params map[string]any, jsonBody any) (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, path, characterID, params, jsonBody)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockESIClientMockRecorder) Delete(ctx, path, characterID, params, jsonBody any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockESIClient)(nil).Delete), ctx, path, characterID, params, jsonBody)
}

// ForUser mocks base method.
func (m *MockESIClient) ForUser(auth esi.TokenSource) esi.Client {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ForUser", auth)
	ret0, _ := ret[0].(esi.Client)
	return ret0
}

// ForUser indicates an expected call of ForUser.
func (mr *MockESIClientMockRecorder) ForUser(auth any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ForUser", reflect.TypeOf((*MockESIClient)(nil).ForUser), auth)
}

// Get mocks base method.
func (m *MockESIClient) Get(ctx context.Context, path string, characterID *int, params map[string]any, cacheTTL *float64) (esi.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, path, characterID, params, cacheTTL)
	ret0, _ := ret[0].(esi.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockESIClientMockRecorder) Get(ctx, path, characterID, params, cacheTTL any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockESIClient)(nil).Get), ctx, path, characterID, params, cacheTTL)
}

// GetAllPages mocks base method.
func (m *MockESIClient) GetAllPages(ctx context.Context, path string, characterID *int, params map[string]any, maxPages int) (esi.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllPages", ctx, path, characterID, params, maxPages)
	ret0, _ := ret[0].(esi.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllPages indicates an expected call of GetAllPages.
func (mr *MockESIClientMockRecorder) GetAllPages(ctx, path, characterID, params, maxPages any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllPages", reflect.TypeOf((*MockESIClient)(nil).GetAllPages), ctx, path, characterID, params, maxPages)
}

// GetCursorPages mocks base method.
func (m *MockESIClient) GetCursorPages(ctx context.Context, path string, q esi.CursorQuery) (esi.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCursorPages", ctx, path, q)
	ret0, _ := ret[0].(esi.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCursorPages indicates an expected call of GetCursorPages.
func (mr *MockESIClientMockRecorder) GetCursorPages(ctx, path, q any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCursorPages", reflect.TypeOf((*MockESIClient)(nil).GetCursorPages), ctx, path, q)
}

// Post mocks base method.
func (m *MockESIClient) Post(ctx context.Context, path string, characterID *int, params map[string]any, jsonBody any) (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Post", ctx, path, characterID, params, jsonBody)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Post indicates an expected call of Post.
func (mr *MockESIClientMockRecorder) Post(ctx, path, characterID, params, jsonBody any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Post", reflect.TypeOf((*MockESIClient)(nil).Post), ctx, path, characterID, params, jsonBody)
}

// Put mocks base method.
func (m *MockESIClient) Put(ctx context.Context, path string, characterID *int, params map[string]any, jsonBody any) (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Put", ctx, path, characterID, params, jsonBody)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Put indicates an expected call of Put.
func (mr *MockESIClientMockRecorder) Put(ctx, path, characterID, params, jsonBody any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Put", reflect.TypeOf((*MockESIClient)(nil).Put), ctx, path, characterID, params, jsonBody)
}

// MockESITokenSource is a mock of TokenSource interface.
type MockESITokenSource struct {
	ctrl     *gomock.Controller
	recorder *MockESITokenSourceMockRecorder
	isgomock struct{}
}

// MockESITokenSourceMockRecorder is the mock recorder for MockESITokenSource.
type MockESITokenSourceMockRecorder struct {
	mock *MockESITokenSource
}

// NewMockESITokenSource creates a new mock instance.
func NewMockESITokenSource(ctrl *gomock.Controller) *MockESITokenSource {
	mock := &MockESITokenSource{ctrl: ctrl}
	mock.recorder = &MockESITokenSourceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockESITokenSource) EXPECT() *MockESITokenSourceMockRecorder {
	return m.recorder
}

// AccessToken mocks base method.
func (m *MockESITokenSource) AccessToken(ctx context.Context, characterID int) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AccessToken", ctx, characterID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AccessToken indicates an expected call of AccessToken.
func (mr *MockESITokenSourceMockRecorder) AccessToken(ctx, characterID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AccessToken", reflect.TypeOf((*MockESITokenSource)(nil).AccessToken), ctx, characterID)
}
