// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/truewebber/eve-online-mcp/internal/domain/loginstate (interfaces: Repository)
//
// Generated by this command:
//
//	mockgen -destination=../../mocks/loginstate.go -package=mocks -mock_names=Repository=MockLoginstateRepository github.com/truewebber/eve-online-mcp/internal/domain/loginstate Repository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	loginstate "github.com/truewebber/eve-online-mcp/internal/domain/loginstate"
	gomock "go.uber.org/mock/gomock"
)

// MockLoginstateRepository is a mock of Repository interface.
type MockLoginstateRepository struct {
	ctrl     *gomock.Controller
	recorder *MockLoginstateRepositoryMockRecorder
	isgomock struct{}
}

// MockLoginstateRepositoryMockRecorder is the mock recorder for MockLoginstateRepository.
type MockLoginstateRepositoryMockRecorder struct {
	mock *MockLoginstateRepository
}

// NewMockLoginstateRepository creates a new mock instance.
func NewMockLoginstateRepository(ctrl *gomock.Controller) *MockLoginstateRepository {
	mock := &MockLoginstateRepository{ctrl: ctrl}
	mock.recorder = &MockLoginstateRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLoginstateRepository) EXPECT() *MockLoginstateRepositoryMockRecorder {
	return m.recorder
}

// DeleteExpired mocks base method.
func (m *MockLoginstateRepository) DeleteExpired(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteExpired", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteExpired indicates an expected call of DeleteExpired.
func (mr *MockLoginstateRepositoryMockRecorder) DeleteExpired(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteExpired", reflect.TypeOf((*MockLoginstateRepository)(nil).DeleteExpired), ctx)
}

// Get mocks base method.
func (m *MockLoginstateRepository) Get(ctx context.Context, state string) (*loginstate.Login, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, state)
	ret0, _ := ret[0].(*loginstate.Login)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockLoginstateRepositoryMockRecorder) Get(ctx, state any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockLoginstateRepository)(nil).Get), ctx, state)
}

// Put mocks base method.
func (m *MockLoginstateRepository) Put(ctx context.Context, st loginstate.Login) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Put", ctx, st)
	ret0, _ := ret[0].(error)
	return ret0
}

// Put indicates an expected call of Put.
func (mr *MockLoginstateRepositoryMockRecorder) Put(ctx, st any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Put", reflect.TypeOf((*MockLoginstateRepository)(nil).Put), ctx, st)
}

// Take mocks base method.
func (m *MockLoginstateRepository) Take(ctx context.Context, state string) (*loginstate.Login, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Take", ctx, state)
	ret0, _ := ret[0].(*loginstate.Login)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Take indicates an expected call of Take.
func (mr *MockLoginstateRepositoryMockRecorder) Take(ctx, state any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Take", reflect.TypeOf((*MockLoginstateRepository)(nil).Take), ctx, state)
}
