// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/truewebber/eve-online-mcp/internal/domain/mutation (interfaces: Repository)
//
// Generated by this command:
//
//	mockgen -destination=../../mocks/mutation.go -package=mocks -mock_names=Repository=MockMutationRepository github.com/truewebber/eve-online-mcp/internal/domain/mutation Repository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	mutation "github.com/truewebber/eve-online-mcp/internal/domain/mutation"
	gomock "go.uber.org/mock/gomock"
)

// MockMutationRepository is a mock of Repository interface.
type MockMutationRepository struct {
	ctrl     *gomock.Controller
	recorder *MockMutationRepositoryMockRecorder
	isgomock struct{}
}

// MockMutationRepositoryMockRecorder is the mock recorder for MockMutationRepository.
type MockMutationRepositoryMockRecorder struct {
	mock *MockMutationRepository
}

// NewMockMutationRepository creates a new mock instance.
func NewMockMutationRepository(ctrl *gomock.Controller) *MockMutationRepository {
	mock := &MockMutationRepository{ctrl: ctrl}
	mock.recorder = &MockMutationRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMutationRepository) EXPECT() *MockMutationRepositoryMockRecorder {
	return m.recorder
}

// CountSince mocks base method.
func (m *MockMutationRepository) CountSince(ctx context.Context, characterID int64, since time.Time) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountSince", ctx, characterID, since)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountSince indicates an expected call of CountSince.
func (mr *MockMutationRepositoryMockRecorder) CountSince(ctx, characterID, since any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountSince", reflect.TypeOf((*MockMutationRepository)(nil).CountSince), ctx, characterID, since)
}

// Insert mocks base method.
func (m *MockMutationRepository) Insert(ctx context.Context, mail mutation.Mail) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", ctx, mail)
	ret0, _ := ret[0].(error)
	return ret0
}

// Insert indicates an expected call of Insert.
func (mr *MockMutationRepositoryMockRecorder) Insert(ctx, mail any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockMutationRepository)(nil).Insert), ctx, mail)
}
