// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/truewebber/eve-online-mcp/internal/domain/mutation (interfaces: Repository)
//
// Generated by this command:
//
//	mockgen -destination=../../mocks/mutation.go -package=mocks -mock_names=Repository=MockMutationRepository github.com/truewebber/eve-online-mcp/internal/domain/mutation Repository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	mutation "github.com/truewebber/eve-online-mcp/internal/domain/mutation"
	gomock "go.uber.org/mock/gomock"
)

// MockMutationRepository is a mock of Repository interface.
type MockMutationRepository struct {
	ctrl     *gomock.Controller
	recorder *MockMutationRepositoryMockRecorder
	isgomock struct{}
}

// MockMutationRepositoryMockRecorder is the mock recorder for MockMutationRepository.
type MockMutationRepositoryMockRecorder struct {
	mock *MockMutationRepository
}

// NewMockMutationRepository creates a new mock instance.
func NewMockMutationRepository(ctrl *gomock.Controller) *MockMutationRepository {
	mock := &MockMutationRepository{ctrl: ctrl}
	mock.recorder = &MockMutationRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMutationRepository) EXPECT() *MockMutationRepositoryMockRecorder {
	return m.recorder
}

// Append mocks base method.
func (m_2 *MockMutationRepository) Append(ctx context.Context, m mutation.Mutation) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "Append", ctx, m)
	ret0, _ := ret[0].(error)
	return ret0
}

// Append indicates an expected call of Append.
func (mr *MockMutationRepositoryMockRecorder) Append(ctx, m any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Append", reflect.TypeOf((*MockMutationRepository)(nil).Append), ctx, m)
}

// CountMailCap mocks base method.
func (m *MockMutationRepository) CountMailCap(ctx context.Context, characterID int64) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountMailCap", ctx, characterID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountMailCap indicates an expected call of CountMailCap.
func (mr *MockMutationRepositoryMockRecorder) CountMailCap(ctx, characterID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountMailCap", reflect.TypeOf((*MockMutationRepository)(nil).CountMailCap), ctx, characterID)
}

// HoldMailCap mocks base method.
func (m *MockMutationRepository) HoldMailCap(ctx context.Context, characterID int64) (*mutation.Hold, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HoldMailCap", ctx, characterID)
	ret0, _ := ret[0].(*mutation.Hold)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HoldMailCap indicates an expected call of HoldMailCap.
func (mr *MockMutationRepositoryMockRecorder) HoldMailCap(ctx, characterID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HoldMailCap", reflect.TypeOf((*MockMutationRepository)(nil).HoldMailCap), ctx, characterID)
}
