// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/truewebber/eve-online-mcp/internal/domain/oauthclient (interfaces: Repository)
//
// Generated by this command:
//
//	mockgen -destination=../../mocks/oauthclient.go -package=mocks -mock_names=Repository=MockOauthclientRepository github.com/truewebber/eve-online-mcp/internal/domain/oauthclient Repository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	oauthclient "github.com/truewebber/eve-online-mcp/internal/domain/oauthclient"
	gomock "go.uber.org/mock/gomock"
)

// MockOauthclientRepository is a mock of Repository interface.
type MockOauthclientRepository struct {
	ctrl     *gomock.Controller
	recorder *MockOauthclientRepositoryMockRecorder
	isgomock struct{}
}

// MockOauthclientRepositoryMockRecorder is the mock recorder for MockOauthclientRepository.
type MockOauthclientRepositoryMockRecorder struct {
	mock *MockOauthclientRepository
}

// NewMockOauthclientRepository creates a new mock instance.
func NewMockOauthclientRepository(ctrl *gomock.Controller) *MockOauthclientRepository {
	mock := &MockOauthclientRepository{ctrl: ctrl}
	mock.recorder = &MockOauthclientRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOauthclientRepository) EXPECT() *MockOauthclientRepositoryMockRecorder {
	return m.recorder
}

// DeleteLongSoftDeleted mocks base method.
func (m *MockOauthclientRepository) DeleteLongSoftDeleted(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteLongSoftDeleted", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteLongSoftDeleted indicates an expected call of DeleteLongSoftDeleted.
func (mr *MockOauthclientRepositoryMockRecorder) DeleteLongSoftDeleted(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteLongSoftDeleted", reflect.TypeOf((*MockOauthclientRepository)(nil).DeleteLongSoftDeleted), ctx)
}

// Get mocks base method.
func (m *MockOauthclientRepository) Get(ctx context.Context, id string) (*oauthclient.Client, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(*oauthclient.Client)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockOauthclientRepositoryMockRecorder) Get(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockOauthclientRepository)(nil).Get), ctx, id)
}

// SoftDeleteAbandoned mocks base method.
func (m *MockOauthclientRepository) SoftDeleteAbandoned(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SoftDeleteAbandoned", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SoftDeleteAbandoned indicates an expected call of SoftDeleteAbandoned.
func (mr *MockOauthclientRepositoryMockRecorder) SoftDeleteAbandoned(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SoftDeleteAbandoned", reflect.TypeOf((*MockOauthclientRepository)(nil).SoftDeleteAbandoned), ctx)
}

// Upsert mocks base method.
func (m *MockOauthclientRepository) Upsert(ctx context.Context, c oauthclient.Client) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upsert", ctx, c)
	ret0, _ := ret[0].(error)
	return ret0
}

// Upsert indicates an expected call of Upsert.
func (mr *MockOauthclientRepositoryMockRecorder) Upsert(ctx, c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upsert", reflect.TypeOf((*MockOauthclientRepository)(nil).Upsert), ctx, c)
}
