// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/truewebber/eve-online-mcp/internal/domain/session (interfaces: Repository)
//
// Generated by this command:
//
//	mockgen -destination=../../mocks/session.go -package=mocks -mock_names=Repository=MockSessionRepository github.com/truewebber/eve-online-mcp/internal/domain/session Repository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	session "github.com/truewebber/eve-online-mcp/internal/domain/session"
	gomock "go.uber.org/mock/gomock"
)

// MockSessionRepository is a mock of Repository interface.
type MockSessionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSessionRepositoryMockRecorder
	isgomock struct{}
}

// MockSessionRepositoryMockRecorder is the mock recorder for MockSessionRepository.
type MockSessionRepositoryMockRecorder struct {
	mock *MockSessionRepository
}

// NewMockSessionRepository creates a new mock instance.
func NewMockSessionRepository(ctrl *gomock.Controller) *MockSessionRepository {
	mock := &MockSessionRepository{ctrl: ctrl}
	mock.recorder = &MockSessionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessionRepository) EXPECT() *MockSessionRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockSessionRepository) Create(ctx context.Context, s session.Session) (*session.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, s)
	ret0, _ := ret[0].(*session.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockSessionRepositoryMockRecorder) Create(ctx, s any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockSessionRepository)(nil).Create), ctx, s)
}

// ExpireValidTil mocks base method.
func (m *MockSessionRepository) ExpireValidTil(ctx context.Context) (session.Revoked, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExpireValidTil", ctx)
	ret0, _ := ret[0].(session.Revoked)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExpireValidTil indicates an expected call of ExpireValidTil.
func (mr *MockSessionRepositoryMockRecorder) ExpireValidTil(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExpireValidTil", reflect.TypeOf((*MockSessionRepository)(nil).ExpireValidTil), ctx)
}

// LiveByID mocks base method.
func (m *MockSessionRepository) LiveByID(ctx context.Context, id int64) (*session.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LiveByID", ctx, id)
	ret0, _ := ret[0].(*session.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LiveByID indicates an expected call of LiveByID.
func (mr *MockSessionRepositoryMockRecorder) LiveByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LiveByID", reflect.TypeOf((*MockSessionRepository)(nil).LiveByID), ctx, id)
}

// LockCharacter mocks base method.
func (m *MockSessionRepository) LockCharacter(ctx context.Context, characterID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LockCharacter", ctx, characterID)
	ret0, _ := ret[0].(error)
	return ret0
}

// LockCharacter indicates an expected call of LockCharacter.
func (mr *MockSessionRepositoryMockRecorder) LockCharacter(ctx, characterID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LockCharacter", reflect.TypeOf((*MockSessionRepository)(nil).LockCharacter), ctx, characterID)
}

// LockForRefresh mocks base method.
func (m *MockSessionRepository) LockForRefresh(ctx context.Context, id int64, fn func(string) (string, error)) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LockForRefresh", ctx, id, fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// LockForRefresh indicates an expected call of LockForRefresh.
func (mr *MockSessionRepositoryMockRecorder) LockForRefresh(ctx, id, fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LockForRefresh", reflect.TypeOf((*MockSessionRepository)(nil).LockForRefresh), ctx, id, fn)
}

// PurgeRevoked mocks base method.
func (m *MockSessionRepository) PurgeRevoked(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PurgeRevoked", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PurgeRevoked indicates an expected call of PurgeRevoked.
func (mr *MockSessionRepositoryMockRecorder) PurgeRevoked(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PurgeRevoked", reflect.TypeOf((*MockSessionRepository)(nil).PurgeRevoked), ctx)
}

// Revoke mocks base method.
func (m *MockSessionRepository) Revoke(ctx context.Context, id int64) (session.Revoked, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Revoke", ctx, id)
	ret0, _ := ret[0].(session.Revoked)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Revoke indicates an expected call of Revoke.
func (mr *MockSessionRepositoryMockRecorder) Revoke(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Revoke", reflect.TypeOf((*MockSessionRepository)(nil).Revoke), ctx, id)
}

// RevokeAllForCharacter mocks base method.
func (m *MockSessionRepository) RevokeAllForCharacter(ctx context.Context, characterID int64) (session.Revoked, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeAllForCharacter", ctx, characterID)
	ret0, _ := ret[0].(session.Revoked)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RevokeAllForCharacter indicates an expected call of RevokeAllForCharacter.
func (mr *MockSessionRepositoryMockRecorder) RevokeAllForCharacter(ctx, characterID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeAllForCharacter", reflect.TypeOf((*MockSessionRepository)(nil).RevokeAllForCharacter), ctx, characterID)
}
