// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/truewebber/eve-online-mcp/internal/adapter/sso (interfaces: Client)
//
// Generated by this command:
//
//	mockgen -destination=../../mocks/sso.go -package=mocks -mock_names=Client=MockSSOClient github.com/truewebber/eve-online-mcp/internal/adapter/sso Client
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	sso "github.com/truewebber/eve-online-mcp/internal/adapter/sso"
	gomock "go.uber.org/mock/gomock"
)

// MockSSOClient is a mock of Client interface.
type MockSSOClient struct {
	ctrl     *gomock.Controller
	recorder *MockSSOClientMockRecorder
	isgomock struct{}
}

// MockSSOClientMockRecorder is the mock recorder for MockSSOClient.
type MockSSOClientMockRecorder struct {
	mock *MockSSOClient
}

// NewMockSSOClient creates a new mock instance.
func NewMockSSOClient(ctrl *gomock.Controller) *MockSSOClient {
	mock := &MockSSOClient{ctrl: ctrl}
	mock.recorder = &MockSSOClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSSOClient) EXPECT() *MockSSOClientMockRecorder {
	return m.recorder
}

// AccessToken mocks base method.
func (m *MockSSOClient) AccessToken(ctx context.Context, refreshToken string) (*sso.CharacterToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AccessToken", ctx, refreshToken)
	ret0, _ := ret[0].(*sso.CharacterToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AccessToken indicates an expected call of AccessToken.
func (mr *MockSSOClientMockRecorder) AccessToken(ctx, refreshToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AccessToken", reflect.TypeOf((*MockSSOClient)(nil).AccessToken), ctx, refreshToken)
}

// ExchangeCode mocks base method.
func (m *MockSSOClient) ExchangeCode(ctx context.Context, code, verifier string) (*sso.CharacterToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExchangeCode", ctx, code, verifier)
	ret0, _ := ret[0].(*sso.CharacterToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExchangeCode indicates an expected call of ExchangeCode.
func (mr *MockSSOClientMockRecorder) ExchangeCode(ctx, code, verifier any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExchangeCode", reflect.TypeOf((*MockSSOClient)(nil).ExchangeCode), ctx, code, verifier)
}

// PrepareLogin mocks base method.
func (m *MockSSOClient) PrepareLogin(scopes []string) (*sso.PreparedLogin, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PrepareLogin", scopes)
	ret0, _ := ret[0].(*sso.PreparedLogin)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PrepareLogin indicates an expected call of PrepareLogin.
func (mr *MockSSOClientMockRecorder) PrepareLogin(scopes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PrepareLogin", reflect.TypeOf((*MockSSOClient)(nil).PrepareLogin), scopes)
}

// Revoke mocks base method.
func (m *MockSSOClient) Revoke(ctx context.Context, refreshToken string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Revoke", ctx, refreshToken)
}

// Revoke indicates an expected call of Revoke.
func (mr *MockSSOClientMockRecorder) Revoke(ctx, refreshToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Revoke", reflect.TypeOf((*MockSSOClient)(nil).Revoke), ctx, refreshToken)
}
