// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/truewebber/eve-online-mcp/internal/adapter/sso (interfaces: Client)
//
// Generated by this command:
//
//	mockgen -destination=../../mocks/sso.go -package=mocks -mock_names=Client=MockSSOClient github.com/truewebber/eve-online-mcp/internal/adapter/sso Client
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	sso "github.com/truewebber/eve-online-mcp/internal/adapter/sso"
	character "github.com/truewebber/eve-online-mcp/internal/domain/character"
	gomock "go.uber.org/mock/gomock"
)

// MockSSOClient is a mock of Client interface.
type MockSSOClient struct {
	ctrl     *gomock.Controller
	recorder *MockSSOClientMockRecorder
	isgomock struct{}
}

// MockSSOClientMockRecorder is the mock recorder for MockSSOClient.
type MockSSOClientMockRecorder struct {
	mock *MockSSOClient
}

// NewMockSSOClient creates a new mock instance.
func NewMockSSOClient(ctrl *gomock.Controller) *MockSSOClient {
	mock := &MockSSOClient{ctrl: ctrl}
	mock.recorder = &MockSSOClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSSOClient) EXPECT() *MockSSOClientMockRecorder {
	return m.recorder
}

// AccessToken mocks base method.
func (m *MockSSOClient) AccessToken(ctx context.Context, characterID int) (*sso.CharacterToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AccessToken", ctx, characterID)
	ret0, _ := ret[0].(*sso.CharacterToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AccessToken indicates an expected call of AccessToken.
func (mr *MockSSOClientMockRecorder) AccessToken(ctx, characterID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AccessToken", reflect.TypeOf((*MockSSOClient)(nil).AccessToken), ctx, characterID)
}

// All mocks base method.
func (m *MockSSOClient) All(ctx context.Context) []*sso.CharacterToken {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "All", ctx)
	ret0, _ := ret[0].([]*sso.CharacterToken)
	return ret0
}

// All indicates an expected call of All.
func (mr *MockSSOClientMockRecorder) All(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "All", reflect.TypeOf((*MockSSOClient)(nil).All), ctx)
}

// ExchangeCode mocks base method.
func (m *MockSSOClient) ExchangeCode(ctx context.Context, code, verifier string) (*sso.CharacterToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExchangeCode", ctx, code, verifier)
	ret0, _ := ret[0].(*sso.CharacterToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExchangeCode indicates an expected call of ExchangeCode.
func (mr *MockSSOClientMockRecorder) ExchangeCode(ctx, code, verifier any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExchangeCode", reflect.TypeOf((*MockSSOClient)(nil).ExchangeCode), ctx, code, verifier)
}

// FindByName mocks base method.
func (m *MockSSOClient) FindByName(ctx context.Context, name string) *sso.CharacterToken {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByName", ctx, name)
	ret0, _ := ret[0].(*sso.CharacterToken)
	return ret0
}

// FindByName indicates an expected call of FindByName.
func (mr *MockSSOClientMockRecorder) FindByName(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByName", reflect.TypeOf((*MockSSOClient)(nil).FindByName), ctx, name)
}

// ForCharacter mocks base method.
func (m *MockSSOClient) ForCharacter(characterID int, chars character.Repository) sso.Client {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ForCharacter", characterID, chars)
	ret0, _ := ret[0].(sso.Client)
	return ret0
}

// ForCharacter indicates an expected call of ForCharacter.
func (mr *MockSSOClientMockRecorder) ForCharacter(characterID, chars any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ForCharacter", reflect.TypeOf((*MockSSOClient)(nil).ForCharacter), characterID, chars)
}

// Get mocks base method.
func (m *MockSSOClient) Get(ctx context.Context, id int) *sso.CharacterToken {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(*sso.CharacterToken)
	return ret0
}

// Get indicates an expected call of Get.
func (mr *MockSSOClientMockRecorder) Get(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockSSOClient)(nil).Get), ctx, id)
}

// PrepareLogin mocks base method.
func (m *MockSSOClient) PrepareLogin(scopes []string) (*sso.PreparedLogin, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PrepareLogin", scopes)
	ret0, _ := ret[0].(*sso.PreparedLogin)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PrepareLogin indicates an expected call of PrepareLogin.
func (mr *MockSSOClientMockRecorder) PrepareLogin(scopes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PrepareLogin", reflect.TypeOf((*MockSSOClient)(nil).PrepareLogin), scopes)
}

// Remove mocks base method.
func (m *MockSSOClient) Remove(ctx context.Context, id int) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Remove", ctx, id)
	ret0, _ := ret[0].(bool)
	return ret0
}

// Remove indicates an expected call of Remove.
func (mr *MockSSOClientMockRecorder) Remove(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Remove", reflect.TypeOf((*MockSSOClient)(nil).Remove), ctx, id)
}

// Revoke mocks base method.
func (m *MockSSOClient) Revoke(ctx context.Context, characterID int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Revoke", ctx, characterID)
}

// Revoke indicates an expected call of Revoke.
func (mr *MockSSOClientMockRecorder) Revoke(ctx, characterID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Revoke", reflect.TypeOf((*MockSSOClient)(nil).Revoke), ctx, characterID)
}

// Upsert mocks base method.
func (m *MockSSOClient) Upsert(ctx context.Context, token *sso.CharacterToken) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upsert", ctx, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// Upsert indicates an expected call of Upsert.
func (mr *MockSSOClientMockRecorder) Upsert(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upsert", reflect.TypeOf((*MockSSOClient)(nil).Upsert), ctx, token)
}
