// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/truewebber/eve-online-mcp/internal/usecase/sweep (interfaces: Lock)
//
// Generated by this command:
//
//	mockgen -destination=../../mocks/sweep.go -package=mocks -mock_names=Lock=MockSweepLock github.com/truewebber/eve-online-mcp/internal/usecase/sweep Lock
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockSweepLock is a mock of Lock interface.
type MockSweepLock struct {
	ctrl     *gomock.Controller
	recorder *MockSweepLockMockRecorder
	isgomock struct{}
}

// MockSweepLockMockRecorder is the mock recorder for MockSweepLock.
type MockSweepLockMockRecorder struct {
	mock *MockSweepLock
}

// NewMockSweepLock creates a new mock instance.
func NewMockSweepLock(ctrl *gomock.Controller) *MockSweepLock {
	mock := &MockSweepLock{ctrl: ctrl}
	mock.recorder = &MockSweepLockMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSweepLock) EXPECT() *MockSweepLockMockRecorder {
	return m.recorder
}

// Release mocks base method.
func (m *MockSweepLock) Release(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Release", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Release indicates an expected call of Release.
func (mr *MockSweepLockMockRecorder) Release(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Release", reflect.TypeOf((*MockSweepLock)(nil).Release), ctx)
}

// Try mocks base method.
func (m *MockSweepLock) Try(ctx context.Context) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Try", ctx)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Try indicates an expected call of Try.
func (mr *MockSweepLockMockRecorder) Try(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Try", reflect.TypeOf((*MockSweepLock)(nil).Try), ctx)
}
