// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/truewebber/eve-online-mcp/internal/domain/write (interfaces: Persist)
//
// Generated by this command:
//
//	mockgen -destination=../../mocks/write.go -package=mocks -mock_names=Persist=MockWritePersist github.com/truewebber/eve-online-mcp/internal/domain/write Persist
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	write "github.com/truewebber/eve-online-mcp/internal/domain/write"
	gomock "go.uber.org/mock/gomock"
)

// MockWritePersist is a mock of Persist interface.
type MockWritePersist struct {
	ctrl     *gomock.Controller
	recorder *MockWritePersistMockRecorder
	isgomock struct{}
}

// MockWritePersistMockRecorder is the mock recorder for MockWritePersist.
type MockWritePersistMockRecorder struct {
	mock *MockWritePersist
}

// NewMockWritePersist creates a new mock instance.
func NewMockWritePersist(ctrl *gomock.Controller) *MockWritePersist {
	mock := &MockWritePersist{ctrl: ctrl}
	mock.recorder = &MockWritePersistMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWritePersist) EXPECT() *MockWritePersistMockRecorder {
	return m.recorder
}

// CountConfirm mocks base method.
func (m *MockWritePersist) CountConfirm(ctx context.Context, characterID int64) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountConfirm", ctx, characterID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountConfirm indicates an expected call of CountConfirm.
func (mr *MockWritePersistMockRecorder) CountConfirm(ctx, characterID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountConfirm", reflect.TypeOf((*MockWritePersist)(nil).CountConfirm), ctx, characterID)
}

// CountMailSince mocks base method.
func (m *MockWritePersist) CountMailSince(ctx context.Context, characterID int64, since time.Time) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountMailSince", ctx, characterID, since)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountMailSince indicates an expected call of CountMailSince.
func (mr *MockWritePersistMockRecorder) CountMailSince(ctx, characterID, since any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountMailSince", reflect.TypeOf((*MockWritePersist)(nil).CountMailSince), ctx, characterID, since)
}

// DeleteConfirm mocks base method.
func (m *MockWritePersist) DeleteConfirm(ctx context.Context, token string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteConfirm", ctx, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteConfirm indicates an expected call of DeleteConfirm.
func (mr *MockWritePersistMockRecorder) DeleteConfirm(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteConfirm", reflect.TypeOf((*MockWritePersist)(nil).DeleteConfirm), ctx, token)
}

// GetConfirm mocks base method.
func (m *MockWritePersist) GetConfirm(ctx context.Context, token string) (*write.Confirm, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConfirm", ctx, token)
	ret0, _ := ret[0].(*write.Confirm)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetConfirm indicates an expected call of GetConfirm.
func (mr *MockWritePersistMockRecorder) GetConfirm(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConfirm", reflect.TypeOf((*MockWritePersist)(nil).GetConfirm), ctx, token)
}

// InsertMail mocks base method.
func (m *MockWritePersist) InsertMail(ctx context.Context, characterID int64, at time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertMail", ctx, characterID, at)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertMail indicates an expected call of InsertMail.
func (mr *MockWritePersistMockRecorder) InsertMail(ctx, characterID, at any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertMail", reflect.TypeOf((*MockWritePersist)(nil).InsertMail), ctx, characterID, at)
}

// PutConfirm mocks base method.
func (m *MockWritePersist) PutConfirm(ctx context.Context, c write.Confirm) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PutConfirm", ctx, c)
	ret0, _ := ret[0].(error)
	return ret0
}

// PutConfirm indicates an expected call of PutConfirm.
func (mr *MockWritePersistMockRecorder) PutConfirm(ctx, c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutConfirm", reflect.TypeOf((*MockWritePersist)(nil).PutConfirm), ctx, c)
}
