// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/truewebber/eve-online-mcp/internal/domain/write (interfaces: Persist)
//
// Generated by this command:
//
//	mockgen -destination=../../mocks/write.go -package=mocks -mock_names=Persist=MockWritePersist github.com/truewebber/eve-online-mcp/internal/domain/write Persist
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	write "github.com/truewebber/eve-online-mcp/internal/domain/write"
	gomock "go.uber.org/mock/gomock"
)

// MockWritePersist is a mock of Persist interface.
type MockWritePersist struct {
	ctrl     *gomock.Controller
	recorder *MockWritePersistMockRecorder
	isgomock struct{}
}

// MockWritePersistMockRecorder is the mock recorder for MockWritePersist.
type MockWritePersistMockRecorder struct {
	mock *MockWritePersist
}

// NewMockWritePersist creates a new mock instance.
func NewMockWritePersist(ctrl *gomock.Controller) *MockWritePersist {
	mock := &MockWritePersist{ctrl: ctrl}
	mock.recorder = &MockWritePersistMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWritePersist) EXPECT() *MockWritePersistMockRecorder {
	return m.recorder
}

// AppendMutation mocks base method.
func (m_2 *MockWritePersist) AppendMutation(ctx context.Context, m write.Mutation) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "AppendMutation", ctx, m)
	ret0, _ := ret[0].(error)
	return ret0
}

// AppendMutation indicates an expected call of AppendMutation.
func (mr *MockWritePersistMockRecorder) AppendMutation(ctx, m any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AppendMutation", reflect.TypeOf((*MockWritePersist)(nil).AppendMutation), ctx, m)
}

// CountConfirm mocks base method.
func (m *MockWritePersist) CountConfirm(ctx context.Context, sessionID int64) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountConfirm", ctx, sessionID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountConfirm indicates an expected call of CountConfirm.
func (mr *MockWritePersistMockRecorder) CountConfirm(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountConfirm", reflect.TypeOf((*MockWritePersist)(nil).CountConfirm), ctx, sessionID)
}

// CountMailCap mocks base method.
func (m *MockWritePersist) CountMailCap(ctx context.Context, characterID int64) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountMailCap", ctx, characterID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountMailCap indicates an expected call of CountMailCap.
func (mr *MockWritePersistMockRecorder) CountMailCap(ctx, characterID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountMailCap", reflect.TypeOf((*MockWritePersist)(nil).CountMailCap), ctx, characterID)
}

// DeleteConfirm mocks base method.
func (m *MockWritePersist) DeleteConfirm(ctx context.Context, token string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteConfirm", ctx, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteConfirm indicates an expected call of DeleteConfirm.
func (mr *MockWritePersistMockRecorder) DeleteConfirm(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteConfirm", reflect.TypeOf((*MockWritePersist)(nil).DeleteConfirm), ctx, token)
}

// GetConfirm mocks base method.
func (m *MockWritePersist) GetConfirm(ctx context.Context, token string) (*write.Confirm, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConfirm", ctx, token)
	ret0, _ := ret[0].(*write.Confirm)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetConfirm indicates an expected call of GetConfirm.
func (mr *MockWritePersistMockRecorder) GetConfirm(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConfirm", reflect.TypeOf((*MockWritePersist)(nil).GetConfirm), ctx, token)
}

// HoldMailCap mocks base method.
func (m *MockWritePersist) HoldMailCap(ctx context.Context, characterID int64) (*write.MailCapHold, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HoldMailCap", ctx, characterID)
	ret0, _ := ret[0].(*write.MailCapHold)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HoldMailCap indicates an expected call of HoldMailCap.
func (mr *MockWritePersistMockRecorder) HoldMailCap(ctx, characterID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HoldMailCap", reflect.TypeOf((*MockWritePersist)(nil).HoldMailCap), ctx, characterID)
}

// PutConfirm mocks base method.
func (m *MockWritePersist) PutConfirm(ctx context.Context, c write.Confirm) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PutConfirm", ctx, c)
	ret0, _ := ret[0].(error)
	return ret0
}

// PutConfirm indicates an expected call of PutConfirm.
func (mr *MockWritePersistMockRecorder) PutConfirm(ctx, c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutConfirm", reflect.TypeOf((*MockWritePersist)(nil).PutConfirm), ctx, c)
}
