//go:build go1.22

// Package httpsvc provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package httpsvc

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
)

// OAuthError defines model for OAuthError.
type OAuthError struct {
	Error            *string `json:"error,omitempty"`
	ErrorDescription *string `json:"error_description,omitempty"`
}

// RegisterClient defines model for RegisterClient.
type RegisterClient struct {
	ClientName   *string  `json:"client_name,omitempty"`
	RedirectUris []string `json:"redirect_uris"`
}

// TokenRequest defines model for TokenRequest.
type TokenRequest struct {
	ClientId     *string `json:"client_id,omitempty"`
	Code         *string `json:"code,omitempty"`
	CodeVerifier *string `json:"code_verifier,omitempty"`
	GrantType    *string `json:"grant_type,omitempty"`
	RedirectUri  *string `json:"redirect_uri,omitempty"`
	RefreshToken *string `json:"refresh_token,omitempty"`
}

// TokenResponse defines model for TokenResponse.
type TokenResponse struct {
	AccessToken  *string `json:"access_token,omitempty"`
	ExpiresIn    *int    `json:"expires_in,omitempty"`
	RefreshToken *string `json:"refresh_token,omitempty"`
	Scope        *string `json:"scope,omitempty"`
	TokenType    *string `json:"token_type,omitempty"`
}

// GetAuthCallbackParams defines parameters for GetAuthCallback.
type GetAuthCallbackParams struct {
	Code             *string `form:"code,omitempty" json:"code,omitempty"`
	State            *string `form:"state,omitempty" json:"state,omitempty"`
	Error            *string `form:"error,omitempty" json:"error,omitempty"`
	ErrorDescription *string `form:"error_description,omitempty" json:"error_description,omitempty"`
}

// GetOAuthAuthorizeParams defines parameters for GetOAuthAuthorize.
type GetOAuthAuthorizeParams struct {
	ClientId      *string `form:"client_id,omitempty" json:"client_id,omitempty"`
	RedirectUri   *string `form:"redirect_uri,omitempty" json:"redirect_uri,omitempty"`
	State         *string `form:"state,omitempty" json:"state,omitempty"`
	CodeChallenge *string `form:"code_challenge,omitempty" json:"code_challenge,omitempty"`
}

// PostOAuthRegisterJSONRequestBody defines body for PostOAuthRegister for application/json ContentType.
type PostOAuthRegisterJSONRequestBody = RegisterClient

// PostOAuthTokenFormdataRequestBody defines body for PostOAuthToken for application/x-www-form-urlencoded ContentType.
type PostOAuthTokenFormdataRequestBody = TokenRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Human status page
	// (GET /)
	GetIndex(w http.ResponseWriter, r *http.Request)
	// Authorization server metadata
	// (GET /.well-known/oauth-authorization-server)
	GetAuthorizationServerMetadata(w http.ResponseWriter, r *http.Request)
	// RFC 9728 protected resource metadata
	// (GET /.well-known/oauth-protected-resource)
	GetProtectedResourceMetadata(w http.ResponseWriter, r *http.Request)
	// EVE SSO callback
	// (GET /auth/callback)
	GetAuthCallback(w http.ResponseWriter, r *http.Request, params GetAuthCallbackParams)
	// Redirect to MCP authorize
	// (GET /auth/login)
	GetAuthLogin(w http.ResponseWriter, r *http.Request)
	// MCP authorize — redirects straight to EVE SSO
	// (GET /oauth/authorize)
	GetOAuthAuthorize(w http.ResponseWriter, r *http.Request, params GetOAuthAuthorizeParams)
	// Dynamic client registration
	// (POST /oauth/register)
	PostOAuthRegister(w http.ResponseWriter, r *http.Request)
	// Exchange code or refresh
	// (POST /oauth/token)
	PostOAuthToken(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetIndex operation middleware
func (siw *ServerInterfaceWrapper) GetIndex(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetIndex(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAuthorizationServerMetadata operation middleware
func (siw *ServerInterfaceWrapper) GetAuthorizationServerMetadata(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAuthorizationServerMetadata(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetProtectedResourceMetadata operation middleware
func (siw *ServerInterfaceWrapper) GetProtectedResourceMetadata(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetProtectedResourceMetadata(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAuthCallback operation middleware
func (siw *ServerInterfaceWrapper) GetAuthCallback(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetAuthCallbackParams

	// ------------- Optional query parameter "code" -------------

	err = runtime.BindQueryParameter("form", true, false, "code", r.URL.Query(), &params.Code)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "code", Err: err})
		return
	}

	// ------------- Optional query parameter "state" -------------

	err = runtime.BindQueryParameter("form", true, false, "state", r.URL.Query(), &params.State)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "state", Err: err})
		return
	}

	// ------------- Optional query parameter "error" -------------

	err = runtime.BindQueryParameter("form", true, false, "error", r.URL.Query(), &params.Error)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "error", Err: err})
		return
	}

	// ------------- Optional query parameter "error_description" -------------

	err = runtime.BindQueryParameter("form", true, false, "error_description", r.URL.Query(), &params.ErrorDescription)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "error_description", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAuthCallback(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAuthLogin operation middleware
func (siw *ServerInterfaceWrapper) GetAuthLogin(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAuthLogin(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetOAuthAuthorize operation middleware
func (siw *ServerInterfaceWrapper) GetOAuthAuthorize(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetOAuthAuthorizeParams

	// ------------- Optional query parameter "client_id" -------------

	err = runtime.BindQueryParameter("form", true, false, "client_id", r.URL.Query(), &params.ClientId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "client_id", Err: err})
		return
	}

	// ------------- Optional query parameter "redirect_uri" -------------

	err = runtime.BindQueryParameter("form", true, false, "redirect_uri", r.URL.Query(), &params.RedirectUri)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "redirect_uri", Err: err})
		return
	}

	// ------------- Optional query parameter "state" -------------

	err = runtime.BindQueryParameter("form", true, false, "state", r.URL.Query(), &params.State)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "state", Err: err})
		return
	}

	// ------------- Optional query parameter "code_challenge" -------------

	err = runtime.BindQueryParameter("form", true, false, "code_challenge", r.URL.Query(), &params.CodeChallenge)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "code_challenge", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetOAuthAuthorize(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostOAuthRegister operation middleware
func (siw *ServerInterfaceWrapper) PostOAuthRegister(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostOAuthRegister(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostOAuthToken operation middleware
func (siw *ServerInterfaceWrapper) PostOAuthToken(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostOAuthToken(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("GET "+options.BaseURL+"/{$}", wrapper.GetIndex)
	m.HandleFunc("GET "+options.BaseURL+"/.well-known/oauth-authorization-server", wrapper.GetAuthorizationServerMetadata)
	m.HandleFunc("GET "+options.BaseURL+"/.well-known/oauth-protected-resource", wrapper.GetProtectedResourceMetadata)
	m.HandleFunc("GET "+options.BaseURL+"/auth/callback", wrapper.GetAuthCallback)
	m.HandleFunc("GET "+options.BaseURL+"/auth/login", wrapper.GetAuthLogin)
	m.HandleFunc("GET "+options.BaseURL+"/oauth/authorize", wrapper.GetOAuthAuthorize)
	m.HandleFunc("POST "+options.BaseURL+"/oauth/register", wrapper.PostOAuthRegister)
	m.HandleFunc("POST "+options.BaseURL+"/oauth/token", wrapper.PostOAuthToken)

	return m
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/8xZ23LbyNF+lS78/4XkgCBl7a43zJWW1tpKyRKLlO2LwCWMgCYxq0EPPDMQRbtUlYfI",
	"O+Q98ih5klTPgEdRsuKyd3OjkjCnPnz99Tejz1Guq1oTkrNR/3Nk8xIr4X89P2pceWyMNvxXbXSNxkn0",
	"Y7j47OY1Rv3IOiNpGt3FYeSyQJsbWTupacesu3jxRV/9hrnjdSOcSuvQDJREcvdPzP33SxIV7jzXYCEN",
	"5u6yMdIvkA4ru3Nq+0EYI+beGIMfG2mwiPp/29rnww5LL/Q10gg/NmgftlMWO4/OdYEPDlzeoJETibsD",
	"OzWC3GX4/AX/H5gwMWjLS8fmPzEprau21mTxvq8iz9HaB3eMI7ytpUF7KdeHJTmconmKTXFkc/2Aw37N",
	"Q/G47wx/kjTRPHkDndGwuVIyh9cXF0OwjZmIHEFPAG+wU+V1H3wdwEQbeDMYQsivBUEFuJlOqWwqQfD6",
	"4s0p1GKKNoGLUlqQFp49I+2ePQNXIjitFeTCCaWnSUopXZQIFs2NzBHwttYWLWhCOH53DOekJCHkpTAi",
	"d2igRgO5JsKcbeYTMKVaiTkaEEURVr4dnYIkGDTGagPawECJpsAYrJyS5aGZdKU/QBIbldKV0TOLJvbe",
	"1DK/tiBWx/I5wq2Z8Uza4M3KFvj33/+RkivRILtM2juFpmNlgdBYNvBK3yBIl8ARgVCO5wmwmGsq2nCm",
	"zD9mHgyUzoKekTe7I2kZrdPTN0B4gwZmQl1bNsQi1MKVFpyGQtpc86g2kAulvKMcdpukNGizpmukRbD6",
	"vDEAwGdIo8aoNOpDGpXO1f1u9+D5i6SX9JKD/s8vfvqxW+V1GsFdMEV4FxgM/ryxMygqcaUwYGjvr+Pz",
	"s85oONiPodINOSyA8NaxkT7qUyQ0gj9XzS3nIuOSMCRUt0VEl63IEjiacNgDAH3c22hZpMLyMumkUPIT",
	"ZjGPE2Te4a6S1m194pBkSUpvSTT83cncm5CxbxkYdI0hCz/0DuBPMPp1AH9+8fxnyN6/f985WluQ+XS0",
	"ixjm5HhIk1BqDuLKIjmYGF1B5jOTwRUqPQOrQYtadpjnpkgp5YJIO7AOhfK+Gd04bHcvUShXfso8LrOu",
	"QVHMP2Wg5A2C9tiFRciAfeWAprSXnZxdHI/Ojk4vT0/GF8dnl6/PxxeXw/PRRRZDgRPRKAfZRmp/yvb9",
	"IcJgSkJZ3frQ50Pm/Bly1XBj6mhiD4mzZh2w8Vet1UVKtScRNU9gzXppvcmE1sJe9jmNrBOusWnUTyN9",
	"nUZ3WQykUyqwRiqQ8vl+suauZIwLB7VquGKG2rqpQQu1pOlfQLpF0lL6sXcIM042R4aHYSKksrxZhc7I",
	"3PrdhkZX6EpsLIyOX3pK4wXH45OUArQCrfEma6S4iDDsjYfHA/jXPw8OQtC4kFchS1IaCleCEleorA+d",
	"w6pWwqGN28o1YgaysAmM0UgMk5jcal341L/2ZMrGN8YTYjDw3bEv6SuRXzPhgMFJY7EApaeSYrClNg58",
	"g4xTauiaPH844dBP51NWBB1YRvhxmQObjpSjZ9V5AEIwluvY+xn+xLzUMBgM4WODZg6h1Vimm1cavOyx",
	"S66SZJ0gbiQzsoC3IndqvuR3UdeKq4n5cy8bnJ4cn11cnrzM9hMGv+YC7fIPbbi0IVQ7B6Lla2YS3mc8",
	"Pk9SiuLISae42fFH5iWftqPhSRRHN2hs6HO95DDpcedkEhS1jPrRYdJLDqM48qXKnbHLP6bo7nfJ13rG",
	"x7bMv8SJd20zQW9Hpwmc6VXfSKkQTjDUIWc+tD4p0rPoTBtVdBjxTKDBG5YYPjgnRdSPXqE7oQJvI5YL",
	"QYl4U5/3el5vac9AXgPgreuWrlIrIbtLGtzF264xNEJpeuVgm6oSZs4jHo5hyIOHYy2mloWix1L0gRd0",
	"kxkq1fGwC+nrLNLn/eiEnrgW23suHq3PH/vpb9AJDtyXHV/DU/c3GyT3yn9RFDIw9HBNvTnT4E6RtBmb",
	"ozFUCzs2Y7Nhcdv1V3NXcfLxeDBOtdEOc4eMAasbk+NjURouZo/ayf8TMRqO3mzFZtk/l+7Bwr0vhcgX",
	"/6KWHqzGga5qhQ7tkh89FSYwbrwmh8V1YJM3fH067QXbmpqNmcQMtyDDwjZwZa5pIk0V0uubC9dvK0AW",
	"28NMWLBOGywS+HVB22GrFcWG/YL49WWU0t4PvR50gRsX/+ztJ55aM8+jGXTb39YvkkENvNIpBbLl3eet",
	"lIUgq3eRB+N0sIgnU50RFTo0HPnPEd9MIk/oURyFy2W4pMWPMEi8e51vOF+zMNymv3bhxmX7sU0+fDcG",
	"HSyvCMu2VcAe6TWMLRG5zy3osPf8Pqh/CeiETXC27Zpgg1LBJ+kujn74dk60APVoXVMZMbSKIoZK2kq4",
	"vNyUHFw9V6JYdkA268fvZ1ZDeFsHUmmFUjjw8Hsd6KmFW7cqFrJ3IknaEost3mtFySoSK47bpji/6Zc6",
	"4qmftAXbndgZLQjJadhWUNvkvDaVYbaat9Pa7c0eouR3QslCLCh5Db/MWku+fDs6ae9l91RdSitZF0Dv",
	"1pXkWgNL4L10pW5cuBqmtCK1cC1omRzW3iZKSeEGvpDHrXXS+pcEplG8dbFPsL9qLuTc6tFiF7t6A47W",
	"IvgUfl0+kX0F5W28c/2eJO1f6PJSKIU0xT+IaJep9OwaHgZWEX+YWtcx30LsEfL0ePgvLXu7CSsvKFaZ",
	"gr0VxvZ38+PjAu3/DU6ifvR/3dVzdbd9q+6uPVTvMCyI6XBB22KCjepvKX8hm6wzQk7LjYjtVmyBIEz7",
	"fu1fSbXdwWl8f/emLp66o/DyjNb9oov5NwvH1kv63eYLN2vau3v4PPj91PLCPG4euxD4vXBwQjfM0A9d",
	"Z17OSVQyX6kVtjJk79G8L5+uv5B0/5T+5IzfdmazWWeiTdVpjEJi8imeHomNf1E8CQDfLgub/zPYkQg/",
	"wf4xyfeCbVu03OaloCl6SRmIy/9XYlfaeaHnk9DdGqOiftSN7j7c/ScAAP//aOtxE0kbAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
