//go:build go1.22

// Package httpsvc provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package httpsvc

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
)

// OAuthError defines model for OAuthError.
type OAuthError struct {
	Error            *string `json:"error,omitempty"`
	ErrorDescription *string `json:"error_description,omitempty"`
}

// RegisterClient defines model for RegisterClient.
type RegisterClient struct {
	ClientName   *string  `json:"client_name,omitempty"`
	RedirectUris []string `json:"redirect_uris"`
}

// TokenRequest defines model for TokenRequest.
type TokenRequest struct {
	ClientId     *string `json:"client_id,omitempty"`
	Code         *string `json:"code,omitempty"`
	CodeVerifier *string `json:"code_verifier,omitempty"`
	GrantType    *string `json:"grant_type,omitempty"`
	RedirectUri  *string `json:"redirect_uri,omitempty"`
	RefreshToken *string `json:"refresh_token,omitempty"`
}

// TokenResponse defines model for TokenResponse.
type TokenResponse struct {
	AccessToken  *string `json:"access_token,omitempty"`
	ExpiresIn    *int    `json:"expires_in,omitempty"`
	RefreshToken *string `json:"refresh_token,omitempty"`
	Scope        *string `json:"scope,omitempty"`
	TokenType    *string `json:"token_type,omitempty"`
}

// GetAuthCallbackParams defines parameters for GetAuthCallback.
type GetAuthCallbackParams struct {
	Code             *string `form:"code,omitempty" json:"code,omitempty"`
	State            *string `form:"state,omitempty" json:"state,omitempty"`
	Error            *string `form:"error,omitempty" json:"error,omitempty"`
	ErrorDescription *string `form:"error_description,omitempty" json:"error_description,omitempty"`
}

// GetOAuthAuthorizeParams defines parameters for GetOAuthAuthorize.
type GetOAuthAuthorizeParams struct {
	ClientId      *string `form:"client_id,omitempty" json:"client_id,omitempty"`
	RedirectUri   *string `form:"redirect_uri,omitempty" json:"redirect_uri,omitempty"`
	State         *string `form:"state,omitempty" json:"state,omitempty"`
	CodeChallenge *string `form:"code_challenge,omitempty" json:"code_challenge,omitempty"`
}

// PostOAuthRegisterJSONRequestBody defines body for PostOAuthRegister for application/json ContentType.
type PostOAuthRegisterJSONRequestBody = RegisterClient

// PostOAuthTokenFormdataRequestBody defines body for PostOAuthToken for application/x-www-form-urlencoded ContentType.
type PostOAuthTokenFormdataRequestBody = TokenRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Human status page
	// (GET /)
	GetIndex(w http.ResponseWriter, r *http.Request)
	// Authorization server metadata
	// (GET /.well-known/oauth-authorization-server)
	GetAuthorizationServerMetadata(w http.ResponseWriter, r *http.Request)
	// RFC 9728 protected resource metadata
	// (GET /.well-known/oauth-protected-resource)
	GetProtectedResourceMetadata(w http.ResponseWriter, r *http.Request)
	// EVE SSO callback
	// (GET /auth/callback)
	GetAuthCallback(w http.ResponseWriter, r *http.Request, params GetAuthCallbackParams)
	// Redirect to MCP authorize
	// (GET /auth/login)
	GetAuthLogin(w http.ResponseWriter, r *http.Request)
	// MCP authorize — redirects straight to EVE SSO
	// (GET /oauth/authorize)
	GetOAuthAuthorize(w http.ResponseWriter, r *http.Request, params GetOAuthAuthorizeParams)
	// Dynamic client registration
	// (POST /oauth/register)
	PostOAuthRegister(w http.ResponseWriter, r *http.Request)
	// Exchange code or refresh
	// (POST /oauth/token)
	PostOAuthToken(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetIndex operation middleware
func (siw *ServerInterfaceWrapper) GetIndex(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetIndex(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAuthorizationServerMetadata operation middleware
func (siw *ServerInterfaceWrapper) GetAuthorizationServerMetadata(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAuthorizationServerMetadata(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetProtectedResourceMetadata operation middleware
func (siw *ServerInterfaceWrapper) GetProtectedResourceMetadata(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetProtectedResourceMetadata(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAuthCallback operation middleware
func (siw *ServerInterfaceWrapper) GetAuthCallback(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetAuthCallbackParams

	// ------------- Optional query parameter "code" -------------

	err = runtime.BindQueryParameter("form", true, false, "code", r.URL.Query(), &params.Code)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "code", Err: err})
		return
	}

	// ------------- Optional query parameter "state" -------------

	err = runtime.BindQueryParameter("form", true, false, "state", r.URL.Query(), &params.State)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "state", Err: err})
		return
	}

	// ------------- Optional query parameter "error" -------------

	err = runtime.BindQueryParameter("form", true, false, "error", r.URL.Query(), &params.Error)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "error", Err: err})
		return
	}

	// ------------- Optional query parameter "error_description" -------------

	err = runtime.BindQueryParameter("form", true, false, "error_description", r.URL.Query(), &params.ErrorDescription)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "error_description", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAuthCallback(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAuthLogin operation middleware
func (siw *ServerInterfaceWrapper) GetAuthLogin(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAuthLogin(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetOAuthAuthorize operation middleware
func (siw *ServerInterfaceWrapper) GetOAuthAuthorize(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetOAuthAuthorizeParams

	// ------------- Optional query parameter "client_id" -------------

	err = runtime.BindQueryParameter("form", true, false, "client_id", r.URL.Query(), &params.ClientId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "client_id", Err: err})
		return
	}

	// ------------- Optional query parameter "redirect_uri" -------------

	err = runtime.BindQueryParameter("form", true, false, "redirect_uri", r.URL.Query(), &params.RedirectUri)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "redirect_uri", Err: err})
		return
	}

	// ------------- Optional query parameter "state" -------------

	err = runtime.BindQueryParameter("form", true, false, "state", r.URL.Query(), &params.State)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "state", Err: err})
		return
	}

	// ------------- Optional query parameter "code_challenge" -------------

	err = runtime.BindQueryParameter("form", true, false, "code_challenge", r.URL.Query(), &params.CodeChallenge)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "code_challenge", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetOAuthAuthorize(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostOAuthRegister operation middleware
func (siw *ServerInterfaceWrapper) PostOAuthRegister(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostOAuthRegister(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostOAuthToken operation middleware
func (siw *ServerInterfaceWrapper) PostOAuthToken(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostOAuthToken(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("GET "+options.BaseURL+"/{$}", wrapper.GetIndex)
	m.HandleFunc("GET "+options.BaseURL+"/.well-known/oauth-authorization-server", wrapper.GetAuthorizationServerMetadata)
	m.HandleFunc("GET "+options.BaseURL+"/.well-known/oauth-protected-resource", wrapper.GetProtectedResourceMetadata)
	m.HandleFunc("GET "+options.BaseURL+"/auth/callback", wrapper.GetAuthCallback)
	m.HandleFunc("GET "+options.BaseURL+"/auth/login", wrapper.GetAuthLogin)
	m.HandleFunc("GET "+options.BaseURL+"/oauth/authorize", wrapper.GetOAuthAuthorize)
	m.HandleFunc("POST "+options.BaseURL+"/oauth/register", wrapper.PostOAuthRegister)
	m.HandleFunc("POST "+options.BaseURL+"/oauth/token", wrapper.PostOAuthToken)

	return m
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/8xZ3XLbyNF9lS5834XkgCBl2esNc6Xlam2lZIlFyeuLwEWMgCYxK6AHnhmIpF2qykPk",
	"HfIeeZQ8SapnAP6JlBWXvZsblYT56z59+nTP6HOQqrJShGRN0P8cmDTHUrhfL09qm59qrTT/VWlVobYS",
	"3Ri2n+2iwqAfGKslTYP70I+MMzSplpWVinbMug/bL+rmN0wtrxvhVBqLelBIJPvwxNR9H5Mocee5GjOp",
	"MbXjWku3QFoszc6pzQehtVg4YzR+rKXGLOj/bWufDzssvVa3SCP8WKPZb6fMdh6dqgz3DozvUMuJxN3A",
	"TrUgO/afv+D/ngkTjSYfWzb/iUFpXDWVIoMPfRVpisbs3TEMcF5JjWYs14clWZyifopNYWBStcdht2Yf",
	"Hg+d4U+SJoonb7AzGNY3hUzhzfX1EEytJyJFUBPAO+yUadUHlwcwURreDobg42tAUAZ2pmLK61IQvLl+",
	"ew6VmKKJ4DqXBqSBZ89I2WfPwOYIVqkCUmFFoaZRTDFd5wgG9Z1MEXBeKYMGFCGc/noKl1RIQkhzoUVq",
	"UUOFGlJFhCnbzCdgTFUhFqhBZJlf+W50DpJgUGujNCgNg0LUGYZg5JQMD82kzd0BktiomG60mhnUofOm",
	"kumtAbE6ls8Rds2MZ9J4b1a2wL///o+YbI4a2WVSzinUHSMzhNqwgTfqDkHaCE4IRGF5ngCDqaKsgTNm",
	"/dELb6C0BtSMnNkdSUu0zs/fAuEdapiJ4tawIQahEjY3YBVk0qSKR5WGVBSFc5RhN1FMgyZqqkJqwerz",
	"xgAAnyEOal3EQR/iILe26ne7R89fRb2oFx31f3z1w8tumVZxAPfeFOFcYDK4866sRlGKmwI9hw7+enV5",
	"0RkNB4chlKomixkQzi0b6VCfIqEW/Lms5xyLhFNCkyi6DSO6bEUSwcmEYfcEdLg3aBmkzPAyaaUo5CdM",
	"Qh4nSJzD3UIau/WJIUmimN6RqPm7lakzIWHfEtBoa00GXvSO4E8w+mUAf371/EdI3r9/3zlZW5C4cDSL",
	"mOZkeUiRKIoFiBuDZGGiVQmJi0wCN1ioGRgFSlSywzo3RYopFUTKgrEoCuebVrXFZvccRWHzT4njZdLV",
	"KLLFpwQKeYegHHehhQzYVwY0poPk7OL6dHRxcj4+P7u6Pr0Yv7m8uh4PL0fXSQgZTkRdWEg2QvtDcugO",
	"ERpjEoVRjQ99PmTBnyEtai5MHUXsIXHUjAU2/qaxOoupciJSLCJYs14aZzKhMXCQfI4DY4WtTRz040Dd",
	"xsF9EgKpmDKskDKkdHEYrbkrmePCQlXUnDFDZexUo4FK0vQvIG0btJhe9o5hxsFmZHgYJkIWhjcr0WqZ",
	"GrfbpLa1Rji4Gp4O4F//PDo6dHi/cQrGK2rtVMhtw+nDpLkR6S1nOWic1AYzKNRUUggmV9qCq0phTDXd",
	"kktaKyy66QzdShV9ags3LlNgiJFSdFK28Oj73ObkcSj7PzHNFQwGQ/hYo16A13fDOf5ages1zFIgJBkr",
	"iNV7RgZwLlJbLJaiKqqqYAqzaB0kg/Oz04vr8dnPCWOQdBVnRZd/KM35BD7FGIhGJDl9eZ+rq8sopiAM",
	"rLQFVxj+yGLgkv9keBaEwR1q44tLLzqOelyuWHlEJYN+cBz1ouMgDFx+cDnq8o8p2oel6Y2a8bGN3Pqa",
	"k6N3bTNA70bnEVyolVjHlAkrmF+QsggZFxTppGumdJF1mGasWt4brusOnLMs6Aev0Z5RhvOAa7Qv/87U",
	"572ea3KUS3tXeHFuu7kti1X3uKse34fbrjE1fD64cm3qshR6wSOOjn7IkYexFlPD3ZnjUvCBF3SjGRZF",
	"x9HOh6/Ths/50fGFaA3bBy6erM+/ctPfohUM3JcdX+NT9zfj+9yV/yLLpJfF4VrLZHWNOzuTTWxOrqBs",
	"7djEZsPiptSu5q5wcnjsxanSymJqkTlgVK1TfAylYTt71Ez+n8BoOHq7hc2yaC3dg9a9L0Hkkr/Npb3Z",
	"OFBlVaBFs9RHJ4URXNWuEYa2B9/UDZefVrkuaa2FDFnENOu+5m7Sa2WqaCJ16cPrFJ3zt6n67fYwEwaM",
	"VRqzCH5pZdtvtZJYv5/vOF0axXTwoteDLnC14J+9w8hJa+J0NIFu89v67c2X4NcqJi+2vPui6R/B97K7",
	"xIN5OmjxZKnTokSLmpH/HPB1IHCCHoSBv9H5m1H4iIKEu9e5gvM1C/0V9msXbtxwH9vkw3dT0MGyL1+W",
	"rQwOSK1xbMnIQy5Bx73nD0n9k2cnbJKzKdcEG5IKLkj3YfDi2znRENSxda3LCKHpKEIopSmFTfPNloOz",
	"50ZkywrIZr38fmbVhPPKi0rTKPkDj7/XgU5auHQXWdtrTiRJk2O2pXtNU7JCYqVx2xLnNv1SRTx3k7Zo",
	"u5M7o1aQrILtDmpbnNemMs1W83Zau73ZPkn+VRQyE60kr/GXVWupl+9GZ81l6EFXF9OqrfOkt+ud5FoB",
	"i+C9tLmqrb+PxbQSNd+LN0oOaw8CuSR/7W3b48Y6adz1nWUU5zZ0AXb3u7adW70U7FJXZ8DJGoJP0dfl",
	"u9RXSN7G49LvKdLuWSzNRVEgTfEPEtplKJ26+tv4CvH90rrO+YZij4in48N/adm7TVq5hmIVKThYcexw",
	"tz4+3qD9v8ZJ0A/+r7t6I+42D8TdtdfhHYb5Ztpf0LaUYCP7G8lv2yZjtZDTfAOx3R2bFwjdPBq7p0ll",
	"dmgaX5qdqe37cuCfe9HYn1S2+GZwbD1f328+K3NPe/+An0e/X7fcmsfFYxcDvxcPzuiOFXrfdebnBYlS",
	"pqtuha300Xs07sv34i8E3b1fPzni885sNutMlC47tS6QWHyypyOx8X+BJxHg20Vh86F+RyDcBPPHBN81",
	"bNtNyzzNBU3RtZReuNy/AnaFnRc6PfHVrdZF0A+6wf2H+/8EAAD//z2Hqs6+GgAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
