//go:build go1.22

// Package httpsvc provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package httpsvc

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
)

// OAuthError defines model for OAuthError.
type OAuthError struct {
	Error            *string `json:"error,omitempty"`
	ErrorDescription *string `json:"error_description,omitempty"`
}

// RegisterClient defines model for RegisterClient.
type RegisterClient struct {
	ClientName   *string  `json:"client_name,omitempty"`
	RedirectUris []string `json:"redirect_uris"`
}

// TokenRequest defines model for TokenRequest.
type TokenRequest struct {
	ClientId     *string `json:"client_id,omitempty"`
	Code         *string `json:"code,omitempty"`
	CodeVerifier *string `json:"code_verifier,omitempty"`
	GrantType    *string `json:"grant_type,omitempty"`
	RedirectUri  *string `json:"redirect_uri,omitempty"`
	RefreshToken *string `json:"refresh_token,omitempty"`
}

// TokenResponse defines model for TokenResponse.
type TokenResponse struct {
	AccessToken  *string `json:"access_token,omitempty"`
	ExpiresIn    *int    `json:"expires_in,omitempty"`
	RefreshToken *string `json:"refresh_token,omitempty"`
	Scope        *string `json:"scope,omitempty"`
	TokenType    *string `json:"token_type,omitempty"`
}

// GetAuthCallbackParams defines parameters for GetAuthCallback.
type GetAuthCallbackParams struct {
	Code             *string `form:"code,omitempty" json:"code,omitempty"`
	State            *string `form:"state,omitempty" json:"state,omitempty"`
	Error            *string `form:"error,omitempty" json:"error,omitempty"`
	ErrorDescription *string `form:"error_description,omitempty" json:"error_description,omitempty"`
}

// GetOAuthAuthorizeParams defines parameters for GetOAuthAuthorize.
type GetOAuthAuthorizeParams struct {
	ClientId      *string `form:"client_id,omitempty" json:"client_id,omitempty"`
	RedirectUri   *string `form:"redirect_uri,omitempty" json:"redirect_uri,omitempty"`
	State         *string `form:"state,omitempty" json:"state,omitempty"`
	CodeChallenge *string `form:"code_challenge,omitempty" json:"code_challenge,omitempty"`
}

// PostOAuthRegisterJSONRequestBody defines body for PostOAuthRegister for application/json ContentType.
type PostOAuthRegisterJSONRequestBody = RegisterClient

// PostOAuthTokenFormdataRequestBody defines body for PostOAuthToken for application/x-www-form-urlencoded ContentType.
type PostOAuthTokenFormdataRequestBody = TokenRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Human status page
	// (GET /)
	GetIndex(w http.ResponseWriter, r *http.Request)
	// Authorization server metadata
	// (GET /.well-known/oauth-authorization-server)
	GetAuthorizationServerMetadata(w http.ResponseWriter, r *http.Request)
	// RFC 9728 protected resource metadata
	// (GET /.well-known/oauth-protected-resource)
	GetProtectedResourceMetadata(w http.ResponseWriter, r *http.Request)
	// EVE SSO callback
	// (GET /auth/callback)
	GetAuthCallback(w http.ResponseWriter, r *http.Request, params GetAuthCallbackParams)
	// Redirect to MCP authorize
	// (GET /auth/login)
	GetAuthLogin(w http.ResponseWriter, r *http.Request)
	// MCP authorize — redirects straight to EVE SSO
	// (GET /oauth/authorize)
	GetOAuthAuthorize(w http.ResponseWriter, r *http.Request, params GetOAuthAuthorizeParams)
	// Dynamic client registration
	// (POST /oauth/register)
	PostOAuthRegister(w http.ResponseWriter, r *http.Request)
	// Exchange code or refresh
	// (POST /oauth/token)
	PostOAuthToken(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetIndex operation middleware
func (siw *ServerInterfaceWrapper) GetIndex(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetIndex(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAuthorizationServerMetadata operation middleware
func (siw *ServerInterfaceWrapper) GetAuthorizationServerMetadata(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAuthorizationServerMetadata(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetProtectedResourceMetadata operation middleware
func (siw *ServerInterfaceWrapper) GetProtectedResourceMetadata(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetProtectedResourceMetadata(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAuthCallback operation middleware
func (siw *ServerInterfaceWrapper) GetAuthCallback(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetAuthCallbackParams

	// ------------- Optional query parameter "code" -------------

	err = runtime.BindQueryParameter("form", true, false, "code", r.URL.Query(), &params.Code)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "code", Err: err})
		return
	}

	// ------------- Optional query parameter "state" -------------

	err = runtime.BindQueryParameter("form", true, false, "state", r.URL.Query(), &params.State)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "state", Err: err})
		return
	}

	// ------------- Optional query parameter "error" -------------

	err = runtime.BindQueryParameter("form", true, false, "error", r.URL.Query(), &params.Error)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "error", Err: err})
		return
	}

	// ------------- Optional query parameter "error_description" -------------

	err = runtime.BindQueryParameter("form", true, false, "error_description", r.URL.Query(), &params.ErrorDescription)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "error_description", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAuthCallback(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAuthLogin operation middleware
func (siw *ServerInterfaceWrapper) GetAuthLogin(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAuthLogin(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetOAuthAuthorize operation middleware
func (siw *ServerInterfaceWrapper) GetOAuthAuthorize(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetOAuthAuthorizeParams

	// ------------- Optional query parameter "client_id" -------------

	err = runtime.BindQueryParameter("form", true, false, "client_id", r.URL.Query(), &params.ClientId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "client_id", Err: err})
		return
	}

	// ------------- Optional query parameter "redirect_uri" -------------

	err = runtime.BindQueryParameter("form", true, false, "redirect_uri", r.URL.Query(), &params.RedirectUri)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "redirect_uri", Err: err})
		return
	}

	// ------------- Optional query parameter "state" -------------

	err = runtime.BindQueryParameter("form", true, false, "state", r.URL.Query(), &params.State)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "state", Err: err})
		return
	}

	// ------------- Optional query parameter "code_challenge" -------------

	err = runtime.BindQueryParameter("form", true, false, "code_challenge", r.URL.Query(), &params.CodeChallenge)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "code_challenge", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetOAuthAuthorize(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostOAuthRegister operation middleware
func (siw *ServerInterfaceWrapper) PostOAuthRegister(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostOAuthRegister(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostOAuthToken operation middleware
func (siw *ServerInterfaceWrapper) PostOAuthToken(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostOAuthToken(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("GET "+options.BaseURL+"/{$}", wrapper.GetIndex)
	m.HandleFunc("GET "+options.BaseURL+"/.well-known/oauth-authorization-server", wrapper.GetAuthorizationServerMetadata)
	m.HandleFunc("GET "+options.BaseURL+"/.well-known/oauth-protected-resource", wrapper.GetProtectedResourceMetadata)
	m.HandleFunc("GET "+options.BaseURL+"/auth/callback", wrapper.GetAuthCallback)
	m.HandleFunc("GET "+options.BaseURL+"/auth/login", wrapper.GetAuthLogin)
	m.HandleFunc("GET "+options.BaseURL+"/oauth/authorize", wrapper.GetOAuthAuthorize)
	m.HandleFunc("POST "+options.BaseURL+"/oauth/register", wrapper.PostOAuthRegister)
	m.HandleFunc("POST "+options.BaseURL+"/oauth/token", wrapper.PostOAuthToken)

	return m
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/8xY23IbuRH9lS4kD7LDm61NvGGetFwlZoqSWZS8fthxcUBMk4MVBhgDGFKMi1X5iHxh",
	"viTVmBneNJQU1WadFxUFdAN9OX26B1+ZMFluNGrvWP8rcyLFjIefHy4Kn15aayz9l1uTo/USwx7Wy36d",
	"I+sz563UC7ZplTvTBJ2wMvfS6AapTateMbNfUHjSm+BCOo92oCRq//BGEdanmmfYeK/FRFoUflpYGRSk",
	"x8w1ilYL3Fq+DsZY/FJIiwnr/3x0zucGS2/NHeoJfinQnbZTJo1XC5PgyY3pEq2cS2wO7MJy7afl8hP+",
	"nxCYW3Tp1JP5z0xK5arLjXb40FcuBDp38sQWw/tcWnRTub8ttccF2ufY1GJOmBMOB51T8XjoDC1JPTck",
	"fIBONi5mSgp4f3s7BlfYORfYhwB+mBsLV4MxlEl1kKvCgV8ZSIuMa8j5Al0n0repdCAdvH6tjX/9GnyK",
	"4I1RILjnyiw6kSYhhNHoCjQu0cKKqztHgg4h5z514A0k0glDu8aC4ErB5U+X4SAXThgU1hkLXRgoXiQI",
	"JkcNRiN8nIxgbk1W2QnC6Llc9EkHAOArRKywKmJ9iFjqfd7vdt+8fdfpdXqdN/3v3/3pj91M5BGDTWkn",
	"9+QM+R2MufEWecZnCssYnf395sN1ezIevGpBZgrtMQGpIx1TYq3mquvQLqXALt0VA9cJ2Kq6gyjsJAuH",
	"gjvs4hLjTqQv5h5tFXsKYuWPQ5040pJeciX/gXGLtjXEIThdJZ2vliJdrVH8YlhJn0KMS5xGRa93LhKT",
	"canD73qJC8JBuRR34KPmBR3kpeDkWUyxiSNt0RdWO/iu9wb+AJO/DuDP795+D/GnT5/aF3sacUhVqUVh",
	"JFc13cCVWgOfOXIoJCsOeY9hhsqs+mB4LttEAwvUsDKFSiLtPHIVImFN4bHUo38pOSnXiUK7BZfUznMt",
	"EMxKO8B7LrxaB3wQjHieKzJQGg1n8WA0vLy+nQ5/jAH18lWHLDbkeJf+GEsxBpllmEjuUa2hppeAWcgV",
	"X6MlyNLRNzcfWrBK0WKkfYprUGZBaabE51LcAQeRcsuFR9uBQf3TwcKaIodCJ2iBA6EGbdvJBCNdOLR/",
	"2bo6Q27DfXeoQXBrJZIh3APJgUxCEEZyiRqdCxdn6K0UDpRcIhgdjqphBwQY1GjhLB5e315Ori9G09Hw",
	"5vbyOn7VirQpPFkBnupaGO3J4FZ5bOE8aONhVuUkgTzwh1p3Is1azEuviHcoMGR6KJmL8ZC12BKtKymn",
	"1znv9IjEqIR5LlmfnXd6nXPWYgEURFJd+rPA0GKIdEPqhgnrs7+hH+oE7xkRaMnNQeNtrxc6kAmQC6yI",
	"976b+kztWnsTWW5aR5T4/vZqBM5zX7jApa7IMm7XtBOIr9wK/Ecu84Wj1hnokH0mhW5nhUq177RZ6RJY",
	"7RpYwY92mezHXLzYl78J4lfoecI9f9rxPbR3f3HlELLznyeJLEtyvNfPvC2wsW0cxubihrBV2nEYmwOL",
	"KzjvZHdxCvE4GafcGo/CY9K26ExhBT4WpXEtPamE/y9iNJ5cHcVmS5hb96B276kQBVoiOp9xcfcUYga1",
	"HFWS5RkS0bD+z18ZzSDsS4F2zVqsHCPLcaz1SGW0mvUI/y9SLOfmlyoejNWPHfL5f8YMW/aGbaNI4Ixa",
	"btt5bimvyiykfkXsdt57+3Dc+oGLO+ocNbdXPT50aq7hgCYgJGjTYt/9ag6MyDqYc6kwOcJo1ctA7DBU",
	"4/EYjsHHp7AYrjquw8aYTKruSnE57sPHhbQnSuHbyTVae3zYzuRDC37iSibcozvOSzm9VXd+nAyryasc",
	"yUh2Zs3KheYc6TqCIZl+fybZI5sOfJI+NYWvBr1dnYL0NGjRPOCAV0N2KrUPnabsrw8iHQ652IvCc+p+",
	"+5H2glI8+NL6LckjfCOKlCuFeoHfiADe1+mAM20eZPB02e/jtoLJXmEfyn7UoSHWEDQWDmJ+WBAHRQD/",
	"/ue/9mZV5y2Xi/Tg0uYmU9ZJ/ZkSPnWNayjtsXEl4ur3ClY+H6DzP5hk/V+12N9bnLM++1139wTTrd5f",
	"ukfPIZvDZwpqw5sHKX7z2zX4yfZ7rpmdX+743qtTw71DvSSiOjWB/bjWPJOiBk6ZzjJ7j+Z9+/7wRNLD",
	"e8izM37fXq1W7bmxWbuwCjXVb/L8SBy8Mz0LAL9eFg4ffhoSEQTct0l+eAk77t33IuV6gWFiKBkjPC01",
	"pZ0Uw3BeNojCKtZnXbb5vPlPAAAA///eFm2VDhUAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
