apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Chart.Name | quote }}
  annotations:
    repo: {{ .Values.repo | quote }}
stringData:
  client_id: {{ .Values.app.client_id | quote }}
  client_secret: {{ .Values.app.client_secret | quote }}
  database_url: {{ .Values.app.database_url | quote }}
  hmac_key: {{ .Values.app.hmac_key | quote }}
