apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    release: prometheus
    app: {{ .Chart.Name | quote }}
  annotations:
    repo: {{ .Values.repo | quote }}
spec:
  selector:
    matchLabels:
      app: {{ .Chart.Name | quote }}
  endpoints:
    - port: metrics
